kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ appName }}-canary
spec:
  replicas:
  template:
    metadata:
      name: {{ appName }}
      labels:
        app: {{ appName }}
        env: canary
    spec:
      containers:
      - name: {{ appName }}
        image: gcr.io/{{ project }}/{{ appName }}:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: {{ port }}